###register request
Send Request
Post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "",
    "email": "",
    "mobile": "",
    "password": "",
    "confirm_password": ""
}

###login request
Send Request
Post http://localhost:3000/auth/login
Content-Type: application/json
Authorization : {{$dotenv TOKEN}}

{
    "username": "",
    "password": ""
    
}